name: medic
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.7.0
  http: ^0.12.0+4

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/img/
    - assets/fonts/
    - assets/fonts/montserrat/
    - assets/fonts/poppins/
  fonts:
    - family: Monsterrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf

    - family: Monsterrat Medium
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf

    - family: Monsterrat SemiBold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf

    - family: Monsterrat Bold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf

    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf

    - family: Poppins Light
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf

    - family: Poppins Italic
      fonts:
        - asset: assets/fonts/poppins/Poppins-Italic.ttf

    - family: Poppins SemiBold
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf

    - family: Poppins Bold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf

